#!/usr/bin/python
import subprocess
import os

com1 = "aptitude search ~i!~M | awk {'print $2'}"
com2 = "awk {'print $2'}"

p1 = subprocess.Popen(com1, shell=True, stdout=subprocess.PIPE)
p2 = subprocess.Popen(com2, shell=True, stdin=p1.stdout)
p1.stdout.close()
p2.communicate()

for i in p2.communicate:
        com3 = "man i"
        com4 = "wc -l"
        p3=subprocess.Popen(com3, shell=True,stdout=subprocess.PIPE)
        p4=subprocess.Popen(com4, shell=True, stdin=p3.stdout)
        p3.stdout.close()
        p4.communicate()
#  print i

#for x in $(aptitude search '~i!~M' | awk {'print $2'})
#do
#   count=`man $x | wc -l`
#   if !  (( "$count" =~ ^[0-9]+$ )); then echo $count; fi
#done
